### ISSUE TITLE
How to keep ollama running in a docker container

### ISSUE THREAD

**Issue by shahriyardx** [jmorganca/ollama#1018]
I am using docker to run ollama locally, but each time I have to do 
```
docker exec -it ollama ollama run llama2
```

I don't want that, I want it to keep running and use the api it exposes

docker-compose.yml
```yml
version: '3.9'

services:
  ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ./data:/root/.ollama
```

**Comment by pepperoni21** [comment]
I think you can run `ollama serve` instead

**Comment by pepperoni21** [comment]
> > I think you can run `ollama serve` instead
> 
> Can you give example of a docker-compose?

Actually just running the docker image as you're doing starts the server, so you should be able to access the api since you exposed the port.

**Comment by mxyng** [comment]
> docker exec -it ollama ollama run llama2

This command enters an running docker container and runs llama2. The server is already running and exposing the port on 0.0.0.0:11434. You can check with `docker ps -f name=ollama`

**Comment by krimple** [comment]
This is old, but so far I have

```
  ollama:
    container_name: ollama
    image: ollama/ollama
    command: serve
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
```

where 

- volumes needed a local folder ollama, where it creates the keys and models folder
- the ports command for 11434 exposes the ollama port to the desktop cli as long as you aren't running native ollama services

And now I get (using colima) 
```
ollama           | 2024/02/01 16:47:30 payload_common.go:145: INFO Dynamic LLM libraries [cuda_v11 cpu]
ollama           | 2024/02/01 16:47:30 gpu.go:94: INFO Detecting GPU type
ollama           | 2024/02/01 16:47:30 gpu.go:236: INFO Searching for GPU management library libnvidia-ml.so
ollama           | 2024/02/01 16:47:30 gpu.go:282: INFO Discovered GPU libraries: []
ollama           | 2024/02/01 16:47:30 gpu.go:236: INFO Searching for GPU management library librocm_smi64.so
ollama           | 2024/02/01 16:47:30 gpu.go:282: INFO Discovered GPU libraries: []
ollama           | 2024/02/01 16:47:30 cpu_common.go:18: INFO CPU does not have vector extensions
ollama           | 2024/02/01 16:47:30 routes.go:973: INFO no GPU detected
```
when calling (from desktop terminal cli)
```
ollama run mistral
```
