### ISSUE TITLE
[Question]: Use all CPU resource from Docker CPU image

### ISSUE THREAD

**Issue by LWJerri** [jmorganca/ollama#1101]
Hi. I have a dedicated server with an **Intel® Core™ i5-13500** processor ([more info here](https://www.hetzner.com/dedicated-rootserver/ex44)). But Ollama uses only ~50% of all power. What do I need to do to use all CPU resources? I'm using Docker to run Ollama, here is my `docker-compose.yaml`:

```yaml
version: "3.7"

services:
  api-ollama:
    restart: always
    image: ollama/ollama:latest
    networks:
      - caddy
    volumes:
      - ollama:/root/.ollama
    labels:
      caddy: api.ollama.main.lwjerri.dev
      caddy.reverse_proxy: "{{upstreams 11434}}"

volumes:
  ollama:

networks:
  caddy:
    external: true
```

![image](https://github.com/jmorganca/ollama/assets/50290430/5941f603-bdd4-49a4-9483-5ab590c0e502)

Thanks for any help <3
