### ISSUE TITLE
Cache models for system restarts to not download again in docker

### ISSUE THREAD

**Issue by peteh** [jmorganca/ollama#1214]
I wrote a docker compose file and thought I mapped the right cache folder. 
However after a system restart, the model is downloaded again. 

My goal is to map the model cache dir to my local disk so when using the same model after a restart, it is not redownloaded again. 

The .ollama folder contains a lot of sha256 files which seem to be the downloaded model files but not the final model. 

My current docker file: 
```
version: '3'
services:
  ollama:
    build: .
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ./ollama:/root/.ollama
```
