### ISSUE TITLE
Is there a health check endpoint?

### ISSUE THREAD

**Issue by jamesbraza** [jmorganca/ollama#1378]
Is there a health check endpoint for the Ollama server? And if yes, where can I find docs on it?

Alternately, is there a currently existing endpoint that can function as a health check?

**Comment by technovangelist** [comment]
Depends on what you are asking for. There is and endpoint at / that lets you know that the server is running. Is that good enough for your needs?

**Comment by jamesbraza** [comment]
Oh nice, that's exactly what is needed, thank you!

```bash
> curl localhost:11434
Ollama is running
```

**Comment by jamesbraza** [comment]
It's worth mentioning for posterity that https://github.com/ollama/ollama/pull/2045 poses a possible health check implementation that uses bash sockets:

```yaml
    healthcheck:
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/11434'"
```

**Comment by icfly2** [comment]
This sadly doesn't help.

I have a situation where ollama responds with ollama is running when queried, but hitting /api/generate results in a timeout.

**Comment by gaardhus** [comment]
I guess `ollama ps` is kind of a health check? https://github.com/ollama/ollama/blob/main/docs/faq.md#how-can-i-tell-if-my-model-was-loaded-onto-the-gpu

**Comment by Martinez1991** [comment]
I had the same problem, I tested it and it worked

`  test: "ollama --version && ollama ps || exit 1"`

**Comment by adamoutler** [comment]
Health check ensuring the service is running and capable of outputting data on port 11434

```
    healthcheck:
      test:  [ "CMD-SHELL", "bash", "-c", "{ printf >&3 'GET / HTTP/1.0\\r\\n\\r\\n'; cat <&3; } 3<>/dev/tcp/localhost/11434 | grep 'Ollama is' || exit 1"  ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

```

**Comment by mcdaqc** [comment]
This **entrypoint.sh** script worked for me:  

```bash
#!/bin/bash

# Start Ollama in the background
/bin/ollama serve &
# Record Process ID
pid=$!

# Pause for Ollama to start
sleep 5

# Extract model name from MODEL variable (removing quotes if present)
MODEL_NAME=$(echo $MODEL | tr -d '"')

# Check if MODEL_NAME has a value
if [ -z "$MODEL_NAME" ]; then
    echo "❌ No model specified in MODEL environment variable"
else
    # Check if model exists
    if ollama list | grep -q "$MODEL_NAME"; then
        echo "🟢 Model ($MODEL_NAME) already installed"
        touch /tmp/ollama_ready  # Creates a temporary file to signal readiness
    else
        echo "🔴 Retrieving model ($MODEL_NAME)..."
        # Attempt to pull model and verify before creating the ready flag
        if ollama pull "$MODEL_NAME" 2>/dev/null && ollama list | grep -q "$MODEL_NAME"; then
            echo "🟢 Model download complete!"
            touch /tmp/ollama_ready  # Mark readiness after successful download
        else
            echo "❌ Error downloading model ($MODEL_NAME)"
        fi
    fi
fi

# Wait for Ollama process to finish
wait $pid
```

And in my `docker-compose.yml`:  

```yaml
ollama:
    image: ollama/ollama:${OLLAMA_HARDWARE:-latest}
    ports:
      - "11434:11434"
    env_file:
      - .env
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-}
    volumes:
      - ollama_data:/root/.ollama
      - ./docker/ollama/entrypoint.sh:/entrypoint.sh
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    restart: always
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]
    healthcheck:
      test: 
        - "CMD-SHELL"
        - |
          test -f /tmp/ollama_ready && \
          bash -c '</dev/tcp/localhost/11434'  # Checks if Ollama is accepting connections
      interval: 10s
      timeout: 10s
      retries: 100
      start_period: 10s
```

- **Temporary file (`/tmp/ollama_ready`)**: Used as a flag to indicate that the model is ready, so the health check knows when Ollama is initialized and the model is listed/downloaded.  
- **`/dev/tcp/localhost/11434`**: This tests if Ollama's API is accessible on port **11434**.

**Comment by evrial** [comment]
Created PR #11393 to add health check

**Comment by YKDZ** [comment]
How about:

```yml
services:
  ollama:
    image: ollama/ollama
    healthcheck:
      test: ollama --version || exit 1
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
```

This works very well for me.
