### ISSUE TITLE
[FEAT] One directory to model them all

### ISSUE THREAD

**Issue by kfsone** [jmorganca/ollama#1451]
Please consider adding a way to allow Ollama to share models with other resources/tools. Either by allowing a "models dir" config setting/option somewhere, or a modelmap.yaml file:

```
- mistral-7b-instruct:
  - presents-as: Mistral-7B-Instruct-v0.1
  - folder: /opt/ai/models/TheBloke/Mistral-7B-Instruct-v01-GGUF  # optional
  - files:
    - tag: Q5_K_M
      file: mistral-7b-instruct-v0.1.Q5_K_M.gguf

- claude2:
  - file: /opt/ai/models/TheBloke/claude2-alpaca-13B-GGUF/claude2-alpaca-13b.Q5_K_M.gguf
```
