### ISSUE TITLE
Support GPU on linux and docker.

### ISSUE THREAD

**Issue by Syulin7** [jmorganca/ollama#797]
I am testing using ollama on linux and docker, and its not using the GPU at all.

it appears that ollma is not using the CUDA image.

I resolved the issue by replacing the base image.

https://github.com/jmorganca/ollama/blob/92578798bb1abcedd6bc99479d804f32d9ee2f6c/Dockerfile#L17-L23

change ubuntu:22.04 to nvidia/cuda:11.8.0-devel-ubuntu22.04

and then it works
![image](https://github.com/jmorganca/ollama/assets/37265556/52f7f99a-2533-4069-b700-7a738f03c7b4)

Perhaps we can build a GPU image and push it to the community, using the "gpu" tag for differentiation.

**Comment by Syulin7** [comment]
@mxyng  PTAL, thanks.

**Comment by missandi** [comment]
> I am testing using ollama on linux and docker, and its not using the GPU at all.
> 
> it appears that ollma is not using the CUDA image.
> 
> I resolved the issue by replacing the base image.
> 
> https://github.com/jmorganca/ollama/blob/92578798bb1abcedd6bc99479d804f32d9ee2f6c/Dockerfile#L17-L23
> 
> change ubuntu:22.04 to nvidia/cuda:11.8.0-devel-ubuntu22.04
> 
> and then it works ![image](https://user-images.githubusercontent.com/37265556/274519256-52f7f99a-2533-4069-b700-7a738f03c7b4.png)
> 
> Perhaps we can build a GPU image and push it to the community, using the "gpu" tag for differentiation.

How to edit it please. Thank you

**Comment by Syulin7** [comment]
In dockerhub image ollama/ollama, GPU actually doesn’t work.
https://hub.docker.com/r/ollama/ollama

```
cp ollama/Dockerfile ollama/Dockerfile.gpu
```
change Line17
https://github.com/jmorganca/ollama/blob/06bcfbd6295b0aa0b4a63b6bd6731c0995f0802d/Dockerfile#L17
to 
```
FROM nvidia/cuda:11.8.0-devel-ubuntu22.04
```
and then build a gpu image
```
docker build -t ollama/ollama:0.1.3-gpu .
```

**Comment by pieroit** [comment]
I just tested (ubuntu 22 + docker nvidia toolkit + RTX 2070) and the docker works fine with GPU:

```
docker run -it --gpus=all -v ./ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama:latest
```

But for some reason it does not if I use it via compose:

```yaml
version: '3.7'

services:

  llm:
    container_name: llm
    image: ollama/ollama:latest
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
```

**Comment by Syulin7** [comment]
> I just tested (ubuntu 22 + docker nvidia toolkit + RTX 2070) and the docker works fine with GPU

@pieroit can you run nvidia-smi, dose it show GPU usage?

it works via compose when use gpu image, like this：
```
services:

  llm:
    image: ollama/ollama:gpu
    volumes:
      - ./.ollama:/root/.ollama
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 
              capabilities: [ gpu ]
```
