### ISSUE TITLE
How to deploy on k8s

### ISSUE THREAD

**Issue by xinmans** [jmorganca/ollama#888]
Anyone can share some deploymen.yaml ?

**Comment by Syulin7** [comment]
@xinmans  This is a example I used for testing.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: llm
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: llm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: llm
    spec:
      containers:
        - image: ollama/ollama
          imagePullPolicy: IfNotPresent
          name: llm
          ports:
            - containerPort: 11434
              protocol: TCP
          resources:
            limits:
              nvidia.com/gpu: "1"
            requests:
              nvidia.com/gpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: llm
  name: ollama
spec:
  ports:
    - name: "11434"
      port: 11434
      targetPort: 11434
  selector:
    app.kubernetes.io/name: llm
  type: ClusterIP
```
